Change 'name' to 'author_name' for Author in models and admin
Because of:
django.db.utils.ProgrammingError: relation "products_author" already exists
after migrate --plan