Change 'author_name' in Author from TextField to ForeignKey(Product)
Because of:
django.db.utils.ProgrammingError: relation "products_author" already exists
when trying to migrate