Remove Author class from models and admin
Because of persistent:
django.db.utils.ProgrammingError: relation "products_author" already exists
when trying to migrate